name: gsm_pay_task
description: "A simple flutter app to demonstrate coding skills for GSM Pay Flutter developer job offer."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # State Management
  get: 4.7.2

  # Api Client
  dio: 5.8.0+1

  # Network Connection
  connectivity_plus: 6.1.4

  # Permission
  permission_handler: 12.0.1
  app_settings: 6.1.1

  # UI
  iconsax_plus: 1.0.0
  flutter_spinkit: 5.2.1
  toastification: 3.0.3
  image_picker: 1.1.2
  image_cropper: 9.1.0

  # Tools
  uuid: 4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting
  flutter_lints: 6.0.0
  very_good_analysis: 9.0.0

flutter:
  disable-swift-package-manager: true
  uses-material-design: true

  fonts:
    - family: IranYekan
      fonts:
        - asset: assets/fonts/IRANYekanMobileRegular.ttf
        - asset: assets/fonts/IRANYekanMobileMedium.ttf
          weight: 500
        - asset: assets/fonts/IRANYekanMobileBold.ttf
          weight: 700
        - asset: assets/fonts/IRANYekanMobileExtraBold.ttf
          weight: 900